### ISSUE TITLE
release an image for 0.9.0

### ISSUE THREAD

**Issue by machine424** [bitnami/bitnami-docker-postgres-exporter#1]
Dear @bitnami-bot,

postgres-exporter [0.9.0](https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.9.0) is out! Could you release a docker image for it?

Thanks.

**Comment by carrodher** [comment]
Hi, thanks for letting us know. It is an automated process, it was released some days ago, see https://github.com/bitnami/bitnami-docker-postgres-exporter/commit/90b64d05390c9694308b23ab02238f26ab483e62

When our tracking system detects a new version in the upstream project, the image is built, tested and released through our internal pipeline.

**Comment by machine424** [comment]
I was expecting bitnami-bot to reply to me.

carrodher I know it's automated, its name is way explicit :)

Four days after the release, I thought maybe the bot needs a human intervention for new versions, it turned out not to be the case.

Thank you to both of you.
